# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
x=np.random.random((3,3,3))
print(x)

[[[8.74515184e-01 4.78182830e-01 8.88023352e-01]
  [4.19856039e-01 2.90163295e-01 6.25293402e-01]
  [4.31936883e-02 8.72451837e-01 8.78093700e-04]]

 [[3.73124090e-01 4.00715059e-01 9.67518096e-01]
  [8.75245299e-01 6.40281337e-01 6.76469663e-01]
  [8.33054612e-01 7.64377967e-01 8.26436550e-01]]

 [[8.49105156e-01 6.62242642e-01 7.72902827e-01]
  [4.99073735e-01 5.35498436e-02 6.19122760e-01]
  [1.65576750e-01 7.46741527e-01 4.78470997e-01]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
z = np.diag(1 +np.arange(4),k=-1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
z = np.zeros((8,8))
z[1::2,::2] =1
z[::2,1::2]=1
print(z)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 4. Normalize a 5x5 random matrix

In [4]:
import numpy as np
x = np.random.random((5,5))
print("Original Array\n")
print(x)
xmax , xmin = x.max() , x.min()
x = (x - xmin)/(x - xmax)

print("After normalization\n")
print(x)

Original Array

[[0.34740397 0.06029381 0.30300216 0.73436363 0.18404484]
 [0.34445933 0.46541867 0.6930827  0.51088959 0.76517899]
 [0.04483992 0.04500098 0.01189355 0.69376589 0.85325021]
 [0.4812256  0.81979398 0.95002691 0.63642831 0.56036216]
 [0.29011957 0.66946317 0.26447021 0.0437857  0.44521242]]
After normalization

[[-0.55675015 -0.05439862 -0.44991882 -3.34999124 -0.22474585]
 [-0.5491803  -0.93585928 -2.65111702 -1.13630982 -4.07516316]
 [-0.03639731 -0.03658174 -0.         -2.66085081 -8.69379356]
 [-1.00113212 -6.20350359         inf -1.99151006 -1.40753975]
 [-0.42161376 -2.3437442  -0.36842563 -0.03519168 -0.85837248]]


c:\users\amit\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in true_divide
  


# 5.  How to find common values between two arrays?

In [5]:
x = np.array([10,20,30,40,60])
y = np.array([30,20,100,122222,12000])
print(x,"\n",y)
z = np.intersect1d(x,y)
print("Common values between 2 array\n",z)

[10 20 30 40 60] 
 [    30     20    100 122222  12000]
Common values between 2 array
 [20 30]


# 6.How to get the dates of yesterday, today and tomorrow?

In [6]:
import numpy as np
yesterday = np.datetime64('today','D') - np.timedelta64(1,'D')
print("yesterday",yesterday)
today = np.datetime64('today','D')
print("today",today)
tommorrow = np.datetime64('today','D') + np.timedelta64(1,'D')
print("tomorrow",tommorrow)

yesterday 2020-07-27
today 2020-07-28
tomorrow 2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [7]:
x = np.random.randint(1,9,6)
y = np.random.randint(1,9,6)
print("first array\n",x)
print("Second Array\n",y)
z = np.allclose(x,y)
print("IS all arrays are equal ",z)

first array
 [3 2 5 6 6 2]
Second Array
 [8 2 5 1 4 8]
IS all arrays are equal  False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [8]:
import numpy as np
x = np.random.random(10)
print("Array\n",x)
x[x.argmax()] = 0
print("Max Array is replaced by\n",x)

Array
 [0.57852935 0.70918045 0.01921129 0.30842257 0.68866431 0.17744312
 0.66679571 0.6808368  0.8433278  0.54749876]
Max Array is replaced by
 [0.57852935 0.70918045 0.01921129 0.30842257 0.68866431 0.17744312
 0.66679571 0.6808368  0.         0.54749876]


# 9. How to print all the values of an array?

In [9]:
np.set_printoptions(threshold=None)
z = np.zeros((5,5))
print(z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [10]:
import numpy as np
x = np.random.random((5,5))
print("Matrix\n",x)
y = x - x.mean(axis =1,keepdims = True)
print("Subtraction after each row of a matrix\n",y)

Matrix
 [[0.05710518 0.14017793 0.10976379 0.99392653 0.08681344]
 [0.34883384 0.86213798 0.43070232 0.08436362 0.15001272]
 [0.33751619 0.20221499 0.54607369 0.80211556 0.91547702]
 [0.01365864 0.85552909 0.66924865 0.99403552 0.97806813]
 [0.33187794 0.70290581 0.30519018 0.54896825 0.80446231]]
Subtraction after each row of a matrix
 [[-0.2204522  -0.13737944 -0.16779359  0.71636916 -0.19074393]
 [-0.02637626  0.48692788  0.05549222 -0.29084648 -0.22519737]
 [-0.2231633  -0.3584645  -0.0146058   0.24143608  0.35479753]
 [-0.68844937  0.15342108 -0.03285936  0.29192751  0.27596013]
 [-0.20680296  0.16422491 -0.23349072  0.01028735  0.26578141]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [11]:
z = np.ones(10)
i = np.random.randint(0,len(z),20)

In [12]:
z += np.bincount(i , minlength = len(z))
print(z)

[1. 2. 5. 5. 4. 3. 3. 2. 3. 2.]


# 12.How to get the diagonal of a dot product?

In [13]:
a = np.random.randint(0,10,(3,3))
print("a\n",a)
b = np.random.randint(0,10,(3,3))
print("b\n",b)
z=np.diag(np.dot(a,b))
print(z)

a
 [[0 4 5]
 [4 4 6]
 [6 3 6]]
b
 [[1 3 3]
 [2 6 7]
 [3 2 7]]
[23 48 81]


# 13.How to find the most frequent value in an array?

In [14]:
Z = np.random.randint(0,10,50)
print (Z)
print('rank:', np.bincount(Z).argmax())

[8 0 6 0 9 2 4 1 2 1 4 7 9 6 8 9 9 2 9 0 6 4 0 3 4 5 8 2 8 4 1 6 9 3 6 6 2
 8 5 5 8 6 1 3 3 8 6 0 5 7]
rank: 6


# 14.How to get the n largest values of an array

In [15]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print ("N largest values of an array\n",Z[np.argsort(Z)[-n:]])

# Fast
print ("N largest values of an array\n",Z[np.argpartition(-Z,n)[:n]])

N largest values of an array
 [9995 9996 9997 9998 9999]
N largest values of an array
 [9998 9999 9997 9996 9995]


# 15.How to create a record array from a regular array?

In [16]:
z = np.array([("hello",3.6,2),
             ("world",2.8,1)])
r = np.core.records.fromarrays(z.T,
                         names = 'col1,col2,col3' ,
                         formats ='S8, f8, i8' )
print(r)

[(b'hello', 3.6, 2) (b'world', 2.8, 1)]
