In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df = pd.read_excel("Linear Regression.xlsx",sheet_name=0)

In [3]:
df.head()

price  sqft_living  bedrooms  bathrooms  floors
0  221900         1180         3       1.00     1.0
1  538000         2570         3       2.25     2.0
2  180000          770         2       1.00     1.0
3  604000         1960         4       3.00     1.0
4  510000         1680         3       2.00     1.0

In [4]:
df.isna().sum()

price          0
sqft_living    0
bedrooms       0
bathrooms      0
floors         0
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   price        21613 non-null  int64  
 1   sqft_living  21613 non-null  int64  
 2   bedrooms     21613 non-null  int64  
 3   bathrooms    21613 non-null  float64
 4   floors       21613 non-null  float64
dtypes: float64(2), int64(3)
memory usage: 844.4 KB


In [6]:
df.corr()

price  sqft_living  bedrooms  bathrooms    floors
price        1.000000     0.702035  0.308350   0.525138  0.256794
sqft_living  0.702035     1.000000  0.576671   0.754665  0.353949
bedrooms     0.308350     0.576671  1.000000   0.515884  0.175429
bathrooms    0.525138     0.754665  0.515884   1.000000  0.500653
floors       0.256794     0.353949  0.175429   0.500653  1.000000

In [7]:
df.hist(figsize=(10,14))

array([[<AxesSubplot:title={'center':'price'}>,
        <AxesSubplot:title={'center':'sqft_living'}>],
       [<AxesSubplot:title={'center':'bedrooms'}>,
        <AxesSubplot:title={'center':'bathrooms'}>],
       [<AxesSubplot:title={'center':'floors'}>, <AxesSubplot:>]],
      dtype=object)

In [8]:
#y_train.shape

In [9]:
#x_test.shape

In [10]:
#y_test.shape

In [11]:
#y_pred1.shape

   ## Linear Regression

In [12]:
x1 = df.iloc[:,1:2]

In [13]:
x1

sqft_living
0             1180
1             2570
2              770
3             1960
4             1680
...            ...
21608         1530
21609         2310
21610         1020
21611         1600
21612         1020

[21613 rows x 1 columns]

In [14]:
y1 = df.iloc[:,:1]

In [15]:
y1

price
0      221900
1      538000
2      180000
3      604000
4      510000
...       ...
21608  360000
21609  400000
21610  402101
21611  400000
21612  325000

[21613 rows x 1 columns]

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
x_train , x_test ,y_train , y_test = train_test_split(x1,y1, test_size = 0.3 , random_state = 12)

In [18]:
from sklearn.linear_model import LinearRegression

In [19]:
model1 = LinearRegression()

In [20]:
model1.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [21]:
y_pred1 = model1.predict(x_test)

In [22]:
y_pred1

array([[503328.13595161],
       [317971.9312659 ],
       [312438.91023051],
       ...,
       [655486.21442495],
       [234976.61573499],
       [389901.20472603]])

In [74]:
plt.scatter(y_test,y_pred1,color=["green";"red"])

SyntaxError: invalid syntax (<ipython-input-74-eb7a81b25f42>, line 1)

In [24]:
unseen = model1.predict(np.array([[1180]]))

In [25]:
unseen

array([[290306.82608893]])

In [26]:
y_pred1.shape

(6484, 1)

In [27]:
y_test.shape

(6484, 1)

In [28]:
from sklearn.metrics import mean_absolute_error

In [29]:
print("mse score",mean_absolute_error(y_test,y_pred1))

mse score 171666.702020506


In [30]:
mean_absolute_error(y_test,y_pred1)


171666.702020506

In [31]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred1)

0.5108518477328099

In [32]:
r2_score(y_test,y_pred1)

0.5108518477328099

In [33]:
r2_score(y_test,np.argmax(y_pred1, axis = 1))


-2.117769921269269

In [34]:
#Linear  Regression between price and bed rooms

In [35]:
df.head()

price  sqft_living  bedrooms  bathrooms  floors
0  221900         1180         3       1.00     1.0
1  538000         2570         3       2.25     2.0
2  180000          770         2       1.00     1.0
3  604000         1960         4       3.00     1.0
4  510000         1680         3       2.00     1.0

In [36]:
x2 = df.iloc[:,2:3]

In [37]:
x2

bedrooms
0             3
1             3
2             2
3             4
4             3
...         ...
21608         3
21609         4
21610         2
21611         3
21612         2

[21613 rows x 1 columns]

In [38]:
model2 = LinearRegression()

In [39]:
x2_train, x2_test , y2_train,y2_test = train_test_split(x2,y1,test_size = 0.3, random_state =12)

In [40]:
model2.fit(x2_train,y2_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [41]:
y_pred2 =model2.predict(x2_test)

In [42]:
print("mse score",mean_absolute_error(y2_test,y_pred2))
from sklearn.metrics import r2_score
print("r2 score",r2_score(y2_test ,y_pred2))

mse score 219258.33118045377
r2 score 0.10898793308542509


## Linear Regression between Price and bathrooms

In [43]:
df.head()

price  sqft_living  bedrooms  bathrooms  floors
0  221900         1180         3       1.00     1.0
1  538000         2570         3       2.25     2.0
2  180000          770         2       1.00     1.0
3  604000         1960         4       3.00     1.0
4  510000         1680         3       2.00     1.0

In [44]:
x3= df.iloc[:,3:4]

In [45]:
x3.head()

bathrooms
0       1.00
1       2.25
2       1.00
3       3.00
4       2.00

In [46]:
x3_train ,x3_test, y3_tain, y3_test= train_test_split(x3,y1, test_size = 0.3 ,random_state =12)

In [47]:
model3 = LinearRegression()

In [48]:
model3.fit(x3_train,y3_tain)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [49]:
y_pred3 = model3.predict(x3_test)

In [50]:
y_pred3

array([[387281.71970156],
       [387281.71970156],
       [448962.96369141],
       ...,
       [634006.69566095],
       [634006.69566095],
       [572325.4516711 ]])

In [51]:
from sklearn.metrics import r2_score
print("r2 score",r2_score(y3_test,y_pred3))
print("mse score",mean_absolute_error(y3_test,y_pred3))

r2 score 0.28120971445114284
mse score 201645.786753719


### Linear Regression between price and floors

In [52]:
x4 = df.iloc[:,-1:]

In [53]:
x4

floors
0         1.0
1         2.0
2         1.0
3         1.0
4         1.0
...       ...
21608     3.0
21609     2.0
21610     2.0
21611     2.0
21612     2.0

[21613 rows x 1 columns]

In [54]:
x4_train ,x4_test, y4_tain, y4_test= train_test_split(x4,y1, test_size = 0.3 ,random_state =12)

In [55]:
model4 = LinearRegression()

In [56]:
model4.fit(x4_train,y4_tain)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [57]:
y_pred4 = model4.predict(x4_test)

In [58]:
y_pred4

array([[455843.83159431],
       [540091.9401441 ],
       [455843.83159431],
       ...,
       [624340.04869388],
       [792836.26579345],
       [792836.26579345]])

In [59]:
from sklearn.metrics import r2_score
print("r2 score",r2_score(y3_test,y_pred3))
print("mse score",mean_absolute_error(y3_test,y_pred3))

r2 score 0.28120971445114284
mse score 201645.786753719


## MultiLinear Regression 

In [60]:
df.head()

price  sqft_living  bedrooms  bathrooms  floors
0  221900         1180         3       1.00     1.0
1  538000         2570         3       2.25     2.0
2  180000          770         2       1.00     1.0
3  604000         1960         4       3.00     1.0
4  510000         1680         3       2.00     1.0

In [61]:
x_5 = df.iloc[:,1:]

In [62]:
x_5.head()

sqft_living  bedrooms  bathrooms  floors
0         1180         3       1.00     1.0
1         2570         3       2.25     2.0
2          770         2       1.00     1.0
3         1960         4       3.00     1.0
4         1680         3       2.00     1.0

In [63]:
x5_train ,x5_test, y5_tain, y5_test= train_test_split(x_5,y1, test_size = 0.3 ,random_state =12)

In [64]:
model5 = LinearRegression()

In [65]:
model5.fit(x5_train,y5_tain)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [66]:
y_pred5 = model5.predict(x5_test)

In [67]:
from sklearn.metrics import r2_score
print("r2 score",r2_score(y5_test,y_pred5))
print("mse score",mean_absolute_error(y5_test,y_pred5))

r2 score 0.5232919906942981
mse score 168983.6395266544
